server {
    listen 80;
    server_name _;
    
    # Set the maximum allowed size of the client request body
    client_max_body_size 64M;

    # Proxy API requests to scheme-master
    location /api/master/ {
        proxy_pass http://scheme-master:9001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
	
	# Proxy API requests to scheme-master
    location /api/pipeline/ {
        proxy_pass http://scheme-pipeline:9002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
	
	# Proxy requests to the frontend service
    location / {
        proxy_pass http://scheme-frontend:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
	
}
