from enum import Enum
from typing import List, Optional, Literal, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field, PastDatetime, AnyUrl, field_validator, ConfigDict
from typing import Literal, IO
import io

ModelProvider = Literal["gemini", "huggingface", "openai"]


class Collection(str, Enum):
    SCHEMES = "schemes"
    USER_DOCUMENTS = "user-documents"
    USERS = "users"
    REFERENCES = "references"
    AUDIT_REQUESTS = "audit-requests"
    GLOBAL_SETTINGS = "global-settings"
    APPLICATIONS = "applications"
    SCHEME_DOCUMENTS = "scheme-documents"
    USER_DOCUMENTS_OCR = "user-documents-ocr"


class UserIdentityDocumentModel(BaseModel):
    title: Optional[str] = None
    filename: Optional[str] = None
    url: Optional[AnyUrl] = None
    uid: Optional[str] = Field(None, description="User ID (stringified ObjectId)")
    date_added: PastDatetime = Field(..., description="Upload timestamp (must be in the past)")
    scheme_slug: Optional[str] = Field(None, description="The slug of the scheme this document is related to.")
    verified: bool = Field(
        False,
        description="Whether OCR verification succeeded"
    )

    @field_validator("date_added", mode="before")
    def parse_date_added(cls, v):
        """Allow ISO strings or datetime objects."""
        if isinstance(v, str):
            try:
                return datetime.fromisoformat(v)
            except ValueError:
                raise ValueError("Invalid date format for date_added; expected ISO format.")
        return v


class DocumentsUploadResponse(BaseModel):
    message: str = Field(..., example="Documents uploaded successfully.")
    uploaded_count: int = Field(..., ge=0, description="Number of documents uploaded.")
    documents: List[UserIdentityDocumentModel] = Field(
        ..., description="Metadata for each uploaded document."
    )


class DocumentsStatusResponse(BaseModel):
    scheme_slug: str = Field(..., description="The scheme slug")
    required_docs: List[str] = Field(..., description="List of docs the scheme requires")
    uploaded: List[UserIdentityDocumentModel] = Field(..., description="Docs the user has uploaded")
    missing: List[str] = Field(..., description="Docs still missing")


class ChatRequest(BaseModel):
    query: str = Field(..., description="User's natural language question.")
    scheme_slug: Optional[str] = Field(None, description="Optional scheme identifier to narrow context.")
    chat_id: Optional[str] = Field(None, description="Optional chat id to persist context (will be given by server on the first hello).")


class ChatResponse(BaseModel):
    response: str = Field(..., description="Answer generated by the chatbot.")
    chat_id: str = Field(..., description="Chat ID of the conversation")


# Application Models

class StartAppRequest(BaseModel):
    scheme_slug: str = Field(..., description="The scheme identifier to apply for")


class UpdateAppRequest(BaseModel):
    title: Optional[str] = Field(
        None, description="Canonical title of the required document"
    )
    old_title: Optional[str] = Field(
        None, description="Original title phrase from the scheme"
    )
    doc_id: str = Field(..., description="MongoDB ObjectId (string) of the uploaded document")
    s3_url: Optional[str] = Field(None, description="S3 URL to access the uploaded document")
    s3_key: Optional[str] = Field(None, description="S3 key used to store/retrieve the document")

    # Pydantic v2 config
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "title": "PAN Card",
                "doc_id": "68b1379771fa8b23607e153d",
                "s3_url": "https://example-bucket.s3.amazonaws.com/users/.../pan.pdf",
                "s3_key": "users/.../pan.pdf"
            }
        }
    )


class ApplicationSummary(BaseModel):
    application_id: str
    scheme_slug: str
    status: Literal["in_progress", "submitted", "rejected", "completed"]
    updated_at: datetime


SCHEME_CATEGORIES= [
    "Business & Entrepreneurship",
    "Science, IT & Communications",
    "Agriculture,Rural & Environment",
    "Travel & Tourism",
    "Skills & Employment",
    "Utility & Sanitation",
    "Transport & Infrastructure",
    "Social welfare & Empowerment",
    "Women and Child",
    "Health & Wellness",
    "Education & Learning",
    "Sports & Culture",
    "Housing & Shelter",
    "Banking,Financial Services and Insurance",
    "Public Safety,Law & Justice"
]


class MyUploadFile:
    """
    A custom class that mimics the behavior and attributes of FastAPI's UploadFile.

    This class is useful for creating in-memory file objects from binary data,
    allowing you to test functions that expect a FastAPI UploadFile object.

    Attributes:
        filename (str): The name of the file.
        content_type (str): The MIME type of the file.
        file (IO[bytes]): An in-memory binary stream (io.BytesIO) of the file content.
    """
    def __init__(self, filename: str, content_type: str, binary_data: bytes):
        self.filename = filename
        self.content_type = content_type
        # Create an in-memory file-like object using io.BytesIO
        self.file: IO[bytes] = io.BytesIO(binary_data)

    def seek(self, offset: int, whence: int = 0) -> None:
        """Seek to a position in the file."""
        self.file.seek(offset, whence)

    def read(self, size: int = -1) -> bytes:
        """Read data from the file."""
        return self.file.read(size)

    def close(self) -> None:
        """Close the file."""
        self.file.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
